### ISSUE TITLE
Adjuntar imagen:

### ISSUE THREAD

**Issue by DonMotoMoto** [waflessnet/tuitanic#10]
A la hora de redactar, SI permite adjuntar una imagen, pero si la quitas y después deseas ponerla de nuevo, ya no la sube, mucho menos te genera un URL de la misma imagen. 
- DonMotoMoto.

**Comment by waflessnet** [comment]
Ya ha sido reportada , gracias 
https://github.com/waflessnet/tuitanic/issues/2#issue-89026661
